Remove static use and use_plugin on the Steamship class
steamship-core/python-client pull request #253
Opened 2022-12-22 14:43 UTC by EniasCailliau

2022-12-23 14:22 UTC, dkolas reviewed
The recreate bit is good, but after our conversation yesterday I don't think we should rip out the static `use` and `use_plugin` methods until we have a clear path for nudging users towards putting new packages in new workspaces.

2022-12-23 14:22 UTC, dkolas commented on src/steamship/client/steamship.py
> +        if recreate:
That turned out not bad :)

2022-12-23 14:22 UTC, dkolas commented on src/steamship/client/steamship.py
> +        If no `instance_handle` is provided, the default is `package_handle`.
I think we should figure out how we want to generally steer people into a new workspace per package before we remove the static methods.

2022-12-30 19:59 UTC, eob requested changes
I definitely think we need another round of UX iteration on the use & use_plugin method calls, but these both seem dangerous to me:

- recreate -> hides deletion of data
- removing the static variants -> makes it extremely easy for two packages to accidentally intermingle data.

With a ton of appreciation for the intent, might be best for us to take this out of the PR list and do some design sketching in notion first since there are so many edge cases to consider first.

2023-01-04 13:09 UTC, closed without merging